#!/bin/bash
echo "Creating html files..."
pydoc3 -w picoscope
pydoc3 -w picoscope.picobase
pydoc3 -w picoscope.ps2000
pydoc3 -w picoscope.ps2000a
pydoc3 -w picoscope.ps3000
pydoc3 -w picoscope.ps3000a
pydoc3 -w picoscope.ps4000
pydoc3 -w picoscope.ps5000a
pydoc3 -w picoscope.ps6000
echo "Moving html files to doc/"
mv *.html doc
echo "Done!"
